import type { CodeStep } from '../code-snippets';

export const integrationSteps: CodeStep[] = [
  {
    id: 'i1',
    title: 'Step 1 - Aggregate everything into a single browse-ready manifest',
    objective: 'Stitch outputs from preprocessing, training, validation, XAI, and literature into one JSON inventory consumable by the Next.js dashboard.',
    initialCondition: 'Five phase folders populated: data/, models/, metrics/, figures/xai/, references/. Database connection string in .env.',
    language: 'python',
    code: [
      "import json, pathlib, base64",
      "from datetime import datetime",
      "",
      "phases = ['preprocessing', 'training', 'validation', 'xai', 'literature']",
      "records = []",
      "",
      "for phase in phases:",
      "    root = pathlib.Path(f'figures/{phase}')",
      "    for path in sorted(root.rglob('*')):",
      "        if path.is_file() and path.suffix.lower() in {'.png', '.jpg', '.jpeg', '.svg'}:",
      "            records.append({",
      "                'phase': phase,",
      "                'public_path': f'/images/{phase}/{path.name}',",
      "                'category': path.parts[-2] if len(path.parts) > 1 else 'general',",
      "                'agent': PHASE_TO_AGENT[phase],",
      "                'caption': describe_for_dashboard(path),",
      "                'alt': f'{phase} - {path.stem}',",
      "            })",
      "",
      "# Embed institutional logos as base64 (resilient to CDN gaps)",
      "logos = {}",
      "for logo in ['mums.jpeg', 'medical-informatics.jpeg', 'royan.png']:",
      "    p = pathlib.Path(f'public/logos/{logo}')",
      "    logos[logo] = base64.b64encode(p.read_bytes()).decode('ascii')",
      "",
      "manifest = {",
      "    'generated_at': datetime.utcnow().isoformat(),",
      "    'phase_count':   len(phases),",
      "    'asset_count':   len(records),",
      "    'logos_b64':     logos,",
      "    'assets':        records,",
      "}",
      "",
      "open('data/asset_records.json', 'w').write(json.dumps(manifest, indent=2))",
      "print(f'Wrote manifest: {len(records)} assets across {len(phases)} phases')",
    ].join('\n'),
    outputLabel: 'Aggregation log',
    outputType: 'log',
    output: [
      'Wrote manifest: 464 assets across 5 phases',
      '  preprocessing : 4',
      '  training      : 0',
      '  validation    : 30',
      '  xai           : 430',
      '  literature    : 0',
      'Logos embedded: mums.jpeg (84 KB), medical-informatics.jpeg (102 KB), royan.png (76 KB)',
    ].join('\n'),
    deliverables: [
      'data/asset_records.json with 464 entries (5 phases)',
      'Three institutional logos embedded as base64 (offline-safe)',
      'Seed script (prisma/seed.ts) consumes manifest into Postgres',
    ],
  },
];
