import type { CodeStep } from '../code-snippets';

export const literatureSteps: CodeStep[] = [
  {
    id: 'l1',
    title: 'Step 1 - Curate 41 high-quality references (2017-2024)',
    objective: 'Build the bibliographic backbone for the dissertation: 41 manually screened references covering microTESE outcomes, AI in andrology, and ML for SR prediction.',
    initialCondition: 'PubMed query: \"microTESE\" OR \"micro-TESE\" OR \"sperm retrieval prediction\" filtered by year >= 2017 yielded 386 hits; abstracts triaged manually.',
    language: 'python',
    code: [
      "import pandas as pd",
      "",
      "refs = pd.read_csv('data/literature/screened_2024.csv')",
      "print(f'Total triaged: {len(refs)}')",
      "print(f'Year range:  {refs[\"year\"].min()} - {refs[\"year\"].max()}')",
      "print(refs.groupby('topic').size().to_string())",
    ].join('\n'),
    outputLabel: 'Triage summary',
    outputType: 'log',
    output: [
      'Total triaged: 41',
      'Year range:  2017 - 2024',
      'topic',
      'AI in andrology              13',
      'Calibration & DCA             4',
      'Hormonal predictors           7',
      'ML methodology                6',
      'Pathology of NOA              5',
      'microTESE outcomes            6',
    ].join('\n'),
    deliverables: [
      '41 references stored as BibTeX in references/dissertation.bib',
      'Topic taxonomy (6 buckets) for visualization on dashboard',
      'Year distribution chart -> figures/literature/year_histogram.svg',
    ],
  },
  {
    id: 'l2',
    title: 'Step 2 - Identify the 7 active research gaps',
    objective: 'Synthesize what the literature does NOT yet cover so the dissertation contribution can be positioned precisely.',
    initialCondition: 'Bibliographic corpus from step 1. Coding methodology: thematic synthesis with 2 reviewers, kappa = 0.84 inter-rater agreement.',
    language: 'python',
    code: [
      "GAPS = [",
      "    {",
      "        'gap': 'Multi-center validation in MENA cohorts',",
      "        'evidence': 'Only 2 of 41 references include MENA data; the rest are EU / North America.',",
      "    },",
      "    {",
      "        'gap': 'Calibration audit for SR prediction',",
      "        'evidence': '0 of 41 references reports decile calibration or DCA; AUC alone reported.',",
      "    },",
      "    {",
      "        'gap': 'Comparative XAI (SHAP + LIME + permutation) bundle',",
      "        'evidence': '4 of 41 references use SHAP; only 1 combines two XAI families.',",
      "    },",
      "    {",
      "        'gap': 'Pathology-aware feature engineering at 16-class resolution',",
      "        'evidence': 'Existing models reduce to 3-4 pathology buckets; classifiers lose granularity.',",
      "    },",
      "    {",
      "        'gap': 'Hormone-ratio interaction terms',",
      "        'evidence': 'FSH/LH and T/E2 ratios appear in 2 references; no interaction analysis.',",
      "    },",
      "    {",
      "        'gap': 'Bootstrap-based clinical CI reporting',",
      "        'evidence': 'Most studies cite point AUC; only 3 of 41 attach 95% CI.',",
      "    },",
      "    {",
      "        'gap': 'Open-source reproducibility packs',",
      "        'evidence': '1 of 41 references shares code; 0 share trained artefacts.',",
      "    },",
      "]",
      "",
      "import json",
      "open('artefacts/literature/research_gaps.json', 'w').write(json.dumps(GAPS, indent=2))",
      "print(f'Gaps recorded: {len(GAPS)}')",
    ].join('\n'),
    outputLabel: 'Gap analysis',
    outputType: 'log',
    output: [
      'Gaps recorded: 7',
      '  G1: Multi-center validation in MENA cohorts',
      '  G2: Calibration audit for SR prediction',
      '  G3: Comparative XAI (SHAP + LIME + permutation) bundle',
      '  G4: Pathology-aware feature engineering at 16-class resolution',
      '  G5: Hormone-ratio interaction terms',
      '  G6: Bootstrap-based clinical CI reporting',
      '  G7: Open-source reproducibility packs',
    ].join('\n'),
    deliverables: [
      '7 research gaps documented in artefacts/literature/research_gaps.json',
      'Each gap mapped to dissertation contributions in mapping_table.md',
      'Gap timeline visualization -> figures/literature/gap_coverage.svg',
    ],
  },
];
