'use client'

import { useState } from 'react'
import BreadcrumbNav from '@/components/breadcrumb-nav'
import { Mic, ChevronDown, ChevronUp, User } from 'lucide-react'
import podcastData from '@/data/content/podcast_data.json'

const HOST_COLORS: Record<string, string> = {
  'Dr. Alex': '#0e7490',
  'Dr. Sarah': '#7c3aed',
}

export default function PodcastPage() {
  const [openSection, setOpenSection] = useState<number | null>(0)

  return (
    <div className="px-4 sm:px-6 lg:px-10 py-8 max-w-screen-2xl mx-auto space-y-8">
      <BreadcrumbNav items={[{ label: 'Research Podcast' }]} />

      <div className="flex items-start gap-4">
        <div className="h-12 w-12 rounded-md bg-primary text-white flex items-center justify-center shadow-md shrink-0">
          <Mic className="h-6 w-6" />
        </div>
        <div>
          <h1 className="font-display font-bold text-3xl tracking-tight">Research Podcast Transcripts</h1>
          <p className="text-sm text-muted-foreground mt-1 max-w-2xl">
            Expert dialogue between Dr. Alex and Dr. Sarah — two AI-trained agents covering every aspect of this NOA study.
          </p>
        </div>
      </div>

      {/* Intro banner */}
      <div className="rounded-xl border border-primary/20 bg-primary/5 p-5">
        <p className="text-sm font-medium text-primary mb-1">Agent Introduction</p>
        <p className="text-sm text-foreground/80 italic">
          &ldquo;{podcastData.intro}&rdquo;
        </p>
      </div>

      {/* Sections */}
      <div className="space-y-3">
        {podcastData.sections.map((section, idx) => {
          const isOpen = openSection === idx
          return (
            <div key={idx} className="rounded-xl border bg-card shadow-sm overflow-hidden">
              <button
                onClick={() => setOpenSection(isOpen ? null : idx)}
                className="w-full flex items-center justify-between p-4 hover:bg-muted/30 transition-colors text-left"
              >
                <div className="flex items-center gap-3">
                  <span className="flex h-7 w-7 items-center justify-center rounded-full bg-primary text-[11px] font-mono font-semibold text-white shrink-0">
                    {idx + 1}
                  </span>
                  <span className="font-display font-semibold text-sm">{section.title}</span>
                </div>
                {isOpen ? <ChevronUp className="h-4 w-4 text-muted-foreground" /> : <ChevronDown className="h-4 w-4 text-muted-foreground" />}
              </button>
              {isOpen && (
                <div className="px-4 pb-5 space-y-3">
                  {section.lines.map((line, li) => {
                    const color = HOST_COLORS[line.speaker] || '#666'
                    const isAlex = line.speaker === 'Dr. Alex'
                    return (
                      <div key={li} className={`flex gap-3 ${isAlex ? '' : 'flex-row-reverse'}`}>
                        <div className="shrink-0 flex flex-col items-center gap-1">
                          <div
                            className="h-8 w-8 rounded-full flex items-center justify-center text-white text-xs font-bold"
                            style={{ backgroundColor: color }}
                          >
                            {isAlex ? 'A' : 'S'}
                          </div>
                          <span className="text-[9px] text-muted-foreground font-mono">{line.speaker.split(' ')[1]}</span>
                        </div>
                        <div
                          className={`rounded-xl px-4 py-3 text-sm leading-relaxed max-w-[85%] ${
                            isAlex
                              ? 'bg-muted/50 rounded-tl-none'
                              : 'bg-primary/5 rounded-tr-none'
                          }`}
                        >
                          {line.text}
                        </div>
                      </div>
                    )
                  })}
                </div>
              )}
            </div>
          )
        })}
      </div>

      {/* Footer note */}
      <div className="text-xs text-muted-foreground text-center py-4">
        8 sections &bull; {podcastData.sections.reduce((a, s) => a + s.lines.length, 0)} dialogue exchanges &bull; Generated by HJR&apos;s Deep Agent
      </div>
    </div>
  )
}
