'use client'

import Link from 'next/link'
import { getIcon } from '@/lib/phases'
import { StatCard } from '@/components/stat-card'
import { Button } from '@/components/ui/button'
import { ArrowRight, Users, Layers, Trophy, Images } from 'lucide-react'
import { ArchitectureBanner } from '@/components/architecture/architecture-banner'
import { HeroVideo } from '@/components/hero-video'
import AIAssistWrapper from '@/components/ai-assist-wrapper'

type Phase = {
  id: number
  iconKey: string
  slug: string
  title: string
  subtitle: string
  accent: string
}

type Counts = { imgs: number }

export default function HomeContent({
  phases,
  counts,
}: {
  phases: Phase[]
  counts: Counts
}) {
  return (
    <div className="px-4 sm:px-6 lg:px-10 py-8 max-w-screen-2xl mx-auto space-y-8">
      {/* Hero Video with Logo Carousel */}
      <HeroVideo />

      <AIAssistWrapper id="home-hero" className="block">
      <section className="rounded-xl border bg-card p-8">
        <h1 className="font-display font-bold text-4xl tracking-tight">NOA microTESE Prediction Dashboard</h1>
        <p className="text-muted-foreground mt-3 max-w-3xl">
          Corrected post-defense pipeline for non-obstructive azoospermia prediction. This dashboard presents
          reproducible outputs generated by AI agents trained by Hossein Jamalirad.
        </p>
        <div className="flex gap-3 mt-5">
          <Button asChild><Link href="/phase/preprocessing">Start pipeline <ArrowRight className="ml-1 h-4 w-4" /></Link></Button>
          <Button asChild variant="outline"><Link href="/cdss">Open CDSS</Link></Button>
        </div>
      </section>
      </AIAssistWrapper>

      <section className="grid grid-cols-2 lg:grid-cols-4 gap-3">
        <AIAssistWrapper id="home-stat-cohort" className="block">
          <StatCard label="Patient Cohort" value="2,413" hint="NOA cases" icon={Users} accent="#0e7490" />
        </AIAssistWrapper>
        <AIAssistWrapper id="home-stat-features" className="block">
          <StatCard label="Features" value="73" hint="55 original + 18 engineered" icon={Layers} accent="#0d9488" />
        </AIAssistWrapper>
        <AIAssistWrapper id="home-stat-best-model" className="block">
          <StatCard label="Best Model (CatBoost)" value="AUC 0.8306" hint="95% CI 0.823–0.845" icon={Trophy} accent="#4f46e5" />
        </AIAssistWrapper>
        <AIAssistWrapper id="home-stat-figures" className="block">
          <StatCard label="Figures" value={String(counts.imgs)} hint="Updated curated visuals" icon={Images} accent="#c026d3" />
        </AIAssistWrapper>
      </section>

      {/* Architecture Banner */}
      <AIAssistWrapper id="home-architecture-banner" className="block">
        <ArchitectureBanner />
      </AIAssistWrapper>

      <AIAssistWrapper id="home-phase-cards" className="block">
      <section className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {phases.map((p) => {
          const Icon = getIcon(p.iconKey)
          return (
            <Link key={p.id} href={`/phase/${p.slug}`} className="rounded-xl border bg-card p-5 hover:border-primary/40 transition-colors">
              <div className="flex items-center gap-3 mb-2">
                <div className="h-9 w-9 rounded-md text-white flex items-center justify-center" style={{ backgroundColor: p.accent }}>
                  <Icon className="h-5 w-5" />
                </div>
                <div>
                  <p className="text-[10px] uppercase tracking-widest text-muted-foreground">Agent {p.id}</p>
                  <p className="font-semibold">{p.title.replace(`Agent ${p.id} — `, '')}</p>
                </div>
              </div>
              <p className="text-xs text-muted-foreground">{p.subtitle}</p>
            </Link>
          )
        })}
      </section>
      </AIAssistWrapper>
    </div>
  )
}
