import Link from 'next/link'
import { prisma } from '@/lib/db'
import { getIcon } from '@/lib/phases'
import { StatCard } from '@/components/stat-card'
import { Button } from '@/components/ui/button'
import { ArrowRight, Users, Layers, Trophy, Images } from 'lucide-react'

async function getPhases() {
  try {
    return await prisma.agentPhase.findMany({ orderBy: { id: 'asc' } })
  } catch {
    return []
  }
}

async function getCounts() {
  try {
    const [imgs] = await Promise.all([prisma.imageAsset.count()])
    return { imgs }
  } catch {
    return { imgs: 0 }
  }
}

export default async function HomePage() {
  const [phases, counts] = await Promise.all([getPhases(), getCounts()])

  return (
    <div className="px-4 sm:px-6 lg:px-10 py-8 max-w-screen-2xl mx-auto space-y-8">
      <section className="rounded-xl border bg-card p-8">
        <h1 className="font-display font-bold text-4xl tracking-tight">NOA microTESE Prediction Dashboard</h1>
        <p className="text-muted-foreground mt-3 max-w-3xl">
          Corrected post-defense pipeline for non-obstructive azoospermia prediction. This dashboard presents
          reproducible outputs generated by AI agents trained by Hossein Jamalirad.
        </p>
        <div className="flex gap-3 mt-5">
          <Button asChild><Link href="/phase/preprocessing">Start pipeline <ArrowRight className="ml-1 h-4 w-4" /></Link></Button>
          <Button asChild variant="outline"><Link href="/cdss">Open CDSS</Link></Button>
        </div>
      </section>

      <section className="grid grid-cols-2 lg:grid-cols-4 gap-3">
        <StatCard label="Screened Cohort" value="2,450" hint="Analytical: 2,413" icon={Users} accent="#0e7490" />
        <StatCard label="Features" value="73" hint="From 55 raw variables" icon={Layers} accent="#0d9488" />
        <StatCard label="Best Model" value="LightGBM" hint="AUC 0.7327 ± 0.0057" icon={Trophy} accent="#4f46e5" />
        <StatCard label="Figures" value={String(counts.imgs)} hint="Updated curated visuals" icon={Images} accent="#c026d3" />
      </section>

      <section className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {phases.map((p) => {
          const Icon = getIcon(p.iconKey)
          return (
            <Link key={p.id} href={`/phase/${p.slug}`} className="rounded-xl border bg-card p-5 hover:border-primary/40 transition-colors">
              <div className="flex items-center gap-3 mb-2">
                <div className="h-9 w-9 rounded-md text-white flex items-center justify-center" style={{ backgroundColor: p.accent }}>
                  <Icon className="h-5 w-5" />
                </div>
                <div>
                  <p className="text-[10px] uppercase tracking-widest text-muted-foreground">Agent {p.id}</p>
                  <p className="font-semibold">{p.title.replace(`Agent ${p.id} — `, '')}</p>
                </div>
              </div>
              <p className="text-xs text-muted-foreground">{p.subtitle}</p>
            </Link>
          )
        })}
      </section>
    </div>
  )
}
